# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/thomas/cmake-3.2.2/bin/cmake

# The command to remove a file.
RM = /home/thomas/cmake-3.2.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/thomas/build/bcv/dsp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/thomas/build/bcv/dsp/LAPACK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/thomas/cmake-3.2.1/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/thomas/cmake-3.2.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/build/bcv/dsp/LAPACK/CMakeFiles /home/thomas/build/bcv/dsp/LAPACK/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/thomas/build/bcv/dsp/LAPACK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named atlas_clean

# Build rule for target.
atlas_clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 atlas_clean
.PHONY : atlas_clean

# fast build rule for target.
atlas_clean/fast:
	$(MAKE) -f CMakeFiles/atlas_clean.dir/build.make CMakeFiles/atlas_clean.dir/build
.PHONY : atlas_clean/fast

#=============================================================================
# Target rules for targets named blis_clean

# Build rule for target.
blis_clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blis_clean
.PHONY : blis_clean

# fast build rule for target.
blis_clean/fast:
	$(MAKE) -f CMakeFiles/blis_clean.dir/build.make CMakeFiles/blis_clean.dir/build
.PHONY : blis_clean/fast

#=============================================================================
# Target rules for targets named dummy

# Build rule for target.
dummy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dummy
.PHONY : dummy

# fast build rule for target.
dummy/fast:
	$(MAKE) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/build
.PHONY : dummy/fast

#=============================================================================
# Target rules for targets named lapack

# Build rule for target.
lapack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lapack
.PHONY : lapack

# fast build rule for target.
lapack/fast:
	$(MAKE) -f CMakeFiles/lapack.dir/build.make CMakeFiles/lapack.dir/build
.PHONY : lapack/fast

#=============================================================================
# Target rules for targets named libblis

# Build rule for target.
libblis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libblis
.PHONY : libblis

# fast build rule for target.
libblis/fast:
	$(MAKE) -f CMakeFiles/libblis.dir/build.make CMakeFiles/libblis.dir/build
.PHONY : libblis/fast

#=============================================================================
# Target rules for targets named libdsp

# Build rule for target.
libdsp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libdsp
.PHONY : libdsp

# fast build rule for target.
libdsp/fast:
	$(MAKE) -f CMakeFiles/libdsp.dir/build.make CMakeFiles/libdsp.dir/build
.PHONY : libdsp/fast

#=============================================================================
# Target rules for targets named libffts

# Build rule for target.
libffts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libffts
.PHONY : libffts

# fast build rule for target.
libffts/fast:
	$(MAKE) -f CMakeFiles/libffts.dir/build.make CMakeFiles/libffts.dir/build
.PHONY : libffts/fast

#=============================================================================
# Target rules for targets named libffts_clean

# Build rule for target.
libffts_clean: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libffts_clean
.PHONY : libffts_clean

# fast build rule for target.
libffts_clean/fast:
	$(MAKE) -f CMakeFiles/libffts_clean.dir/build.make CMakeFiles/libffts_clean.dir/build
.PHONY : libffts_clean/fast

dummy.o: dummy.c.o
.PHONY : dummy.o

# target to build an object file
dummy.c.o:
	$(MAKE) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/dummy.c.o
.PHONY : dummy.c.o

dummy.i: dummy.c.i
.PHONY : dummy.i

# target to preprocess a source file
dummy.c.i:
	$(MAKE) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/dummy.c.i
.PHONY : dummy.c.i

dummy.s: dummy.c.s
.PHONY : dummy.s

# target to generate assembly for a file
dummy.c.s:
	$(MAKE) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/dummy.c.s
.PHONY : dummy.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... lapack"
	@echo "... atlas_clean"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dummy"
	@echo "... blis_clean"
	@echo "... libdsp"
	@echo "... libblis"
	@echo "... libffts_clean"
	@echo "... libffts"
	@echo "... dummy.o"
	@echo "... dummy.i"
	@echo "... dummy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

