include ../../make.inc

MKFILES = Makefile dot/Makefile sum/Makefile axpby/Makefile waxpby/Makefile gemv/Makefile ge_sum_mv/Makefile gbmv/Makefile symv/Makefile spmv/Makefile sbmv/Makefile hemv/Makefile hpmv/Makefile hbmv/Makefile trmv/Makefile tpmv/Makefile trsv/Makefile tbsv/Makefile gemm/Makefile symm/Makefile hemm/Makefile gemv2/Makefile

makefiles: $(MKFILES)




clean:
	rm -f temp *~


